package Novartus;

import Novartus.AddOn.TOTP;
import org.apache.commons.codec.binary.Base32;
import org.apache.commons.codec.binary.Hex;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.io.FileInputStream;
import java.net.URLEncoder;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.SecureRandom;
import java.util.Scanner;

import com.google.zxing.common.ByteMatrix;
import javafx.animation.PauseTransition;
import javafx.scene.layout.StackPane;
import javafx.util.Duration;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;

public class Google_2FA extends Application{
    Stage window;
    public static String QR_Path;
    public static void main(String[] args) throws Exception {

        Scanner scanner= new Scanner(System.in);
        String userid, issuer;
        System.out.println("To Generate 2FA Of An Account, Enter Following Details \n");
        System.out.println("Enter UserId");
        userid=scanner.nextLine();
        System.out.println("Enter Issuer");
        issuer=scanner.nextLine();

        //userid="email@example.com";
        //issuer="github.com/Novartus";
        //Change it to your own userID & issuer


        System.setProperty("java.awt.headless", "true"); // This Allows Application To Access The Graphics Processing Capabilities Of The JVM For Making Graphs / Charts / Images To Display On System.
        String MagicKey = getRandomMagicKey();
        String BarCode = getGoogleAuthenticatorBarCode(MagicKey, userid , issuer);
        String Tmp_Dir = System.getProperty("java.io.tmpdir"); // System Property Indicates The Temporary Directory Used By JVM
        if (!Tmp_Dir.endsWith(File.separator)) {
            Tmp_Dir += File.separator;
        }
        QR_Path = Tmp_Dir + "2FA-QR-Code.png";
        createQRCode(BarCode, QR_Path, 400, 400);

        System.out.println("\n Configure the Google Authenticator App By Scanning The Following QR code:\n");
        System.out.println(QR_Path + "\n");
        System.out.println("If scan is not working then you can also manually add the secret key:\n");
        System.out.println(MagicKey + "\n");
        System.out.println("Once added to your 2FA Application, then verify that the 6 digit codes generated by Google Authenticator Application\n"
                + "are synchronized with the following :\n");


        String lastCode = null;
        launch(args); // Starting Application

        while (true) {
            String code = TOTPCode(MagicKey);
            if (!code.equals(lastCode)) {
                System.out.println(code);
            }
            lastCode = code;
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {}
            finally {
                Files.delete(Paths.get(QR_Path)); // Delete Files on exit
            };
        }
    }

    public static String getRandomMagicKey() {
        SecureRandom secureRandom = new SecureRandom(); // Cryptographically Random Number Generator (RNG)
        byte[] bytes = new byte[20];
        secureRandom.nextBytes(bytes);
        Base32 base32 = new Base32();
        String MagicKey = base32.encodeToString(bytes);
        return MagicKey.toLowerCase().replaceAll("(.{4})(?=.{4})", "$1 ");
    }

    public static String getGoogleAuthenticatorBarCode(String MagicKey, String userid, String issuer) {
        String normalizedBase32Key = MagicKey.replace(" ", "").toUpperCase();
        try { //Encoding URL
            return "otpauth://totp/"
                    + URLEncoder.encode(issuer + ":" + userid, "UTF-8").replace("+", "%20")
                    + "?secret=" + URLEncoder.encode(normalizedBase32Key, "UTF-8").replace("+", "%20")
                    + "&issuer=" + URLEncoder.encode(issuer, "UTF-8").replace("+", "%20");
        } catch (UnsupportedEncodingException e) {
            throw new IllegalStateException(e);
        }
    }

    public static void createQRCode(String barCodeData, String filePath, int height, int width)
            throws WriterException, IOException {
        ByteMatrix matrix = new MultiFormatWriter().encode(barCodeData, BarcodeFormat.QR_CODE,
                width, height);
        try (FileOutputStream out = new FileOutputStream(filePath)) {
            MatrixToImageWriter.writeToStream(matrix, "png", out);
        }
    }

    public static String TOTPCode(String MagicKey) {
        String normalizedBase32Key = MagicKey.replace(" ", "").toUpperCase();
        Base32 base32 = new Base32();
        byte[] bytes = base32.decode(normalizedBase32Key);
        String hexKey = Hex.encodeHexString(bytes);
        long Time = (System.currentTimeMillis() / 1000) / 30;
        String HexTime = Long.toHexString(Time);
        return TOTP.generateTOTP(hexKey, HexTime, "6");
    }

    @Override
    public void start(Stage stage) throws Exception {
    window = stage;

        Image qrcode = new Image(new FileInputStream(QR_Path));
        ImageView imageView = new ImageView(qrcode);
        imageView.setFitHeight(250);
        imageView.setFitWidth(250);
        imageView.setPreserveRatio(true);


        StackPane layout = new StackPane();
        layout.getChildren().add(imageView);
        Scene scene = new Scene(layout, 300,300 );

        PauseTransition delay = new PauseTransition(Duration.seconds(5));
        delay.setOnFinished( event -> window.close() );
        delay.play();

        window.setScene(scene);
        window.setTitle("Google2FA");
        window.show();
    }

    /**
     * @param MagicKey Base32 encoded Secret key
     * @param userid The user's account name OR  email address OR a username OR Whatever you like
     * @param issuer The organization managing this account
     * @see https://github.com/google/google-authenticator/wiki/Key-Uri-Format
     **/
   }
